# 每项配置有以下四个属性：
# template:    模板文件名
# destDir:     目标文件夹
# destPackage: 目标包
# destFileName:目标文件名
#
# 支持如下变量：
# ${basePackage}  在创建文件时该变量将替换为根包名
# ${entityName}   在创建文件时该变量将替换为实体名
templateConfig:

  # InterFaceService层
  - template: java/interfaceservice.vm
    destDir: src/main/java
    destPackage: ${basePackage}.erp.api.service.${entityName}
    destFileName: I${entityName}Service.java


  # Service层
  - template: java/service.vm
    destDir: src/main/java
    destPackage: ${basePackage}.erp.service.impl.${entityName}
    destFileName: ${entityName}Service.java

  # REST-ful Controller
  - template: java/controller.vm
    destDir: src/main/java
    destPackage: com.shushang.erp.controller.${entityName}
    destFileName: ${entityName}Controller.java

  # 生成model.js
  - template: js/models/model.vm
    destDir: src/main/resources
    destPackage: react
    destFileName: ${entityName}.js
#
#  # 生成html列表
#  - template: html/list.vm
#    destDir: src/main/resources
#    destPackage: templates
#    destFileName: list.html
