# 每项配置有以下四个属性：
# template:    模板文件名
# destDir:     目标文件夹
# destPackage: 目标包
# destFileName:目标文件名
#
# 支持如下变量：
# ${basePackage}  在创建文件时该变量将替换为根包名
# ${entityName}   在创建文件时该变量将替换为实体名
templateConfig:

  # InterFaceService层
  - template: java/interfaceservice.vm
    destDir: src/main/java
    destPackage: ${basePackage}.erp.api.service.${entityName}
    destFileName: I${entityName}Service.java

  # Service层
  - template: java/service.vm
    destDir: src/main/java
    destPackage: ${basePackage}.erp.service.impl.${entityName}
    destFileName: ${entityName}ServiceImpl.java

  # REST-ful Controller
  - template: java/controller.vm
    destDir: src/main/java
    destPackage: com.shushang.erp.controller.${entityName}
    destFileName: ${entityName}Controller.java

  # 生成models/index.js
  - template: js/models/index.vm
    destDir: src/main/resources
    destPackage: react/models
    destFileName: index.js

  # 生成models/edit.js
  - template: js/models/edit.vm
    destDir: src/main/resources
    destPackage: react/models
    destFileName: edit.js

  # 生成models/detail.js
  - template: js/models/detail.vm
    destDir: src/main/resources
    destPackage: react/models
    destFileName: detail.js

  # 生成models/add.js
  - template: js/models/add.vm
    destDir: src/main/resources
    destPackage: react/models
    destFileName: add.js

  # 生成service.js
  - template: js/service/service.vm
    destDir: src/main/resources
    destPackage: react/service
    destFileName: ${entityName}.js

  # 生成add/Page.vm
  - template: js/routes/add/Page.vm
    destDir: src/main/resources
    destPackage: react/routes/add
    destFileName: Page.js

  # 生成detail/Page.vm
  - template: js/routes/detail/Page.vm
    destDir: src/main/resources
    destPackage: react/routes/detail
    destFileName: Page.js

  # 生成edit/Page.vm
  - template: js/routes/edit/Page.vm
    destDir: src/main/resources
    destPackage: react/routes/edit
    destFileName: Page.js

  # 生成index/Page.vm
  - template: js/routes/index/Page.vm
    destDir: src/main/resources
    destPackage: react/routes/index
    destFileName: Page.js

  # 生成add.vm
  - template: js/routes/add.vm
    destDir: src/main/resources
    destPackage: react/routes
    destFileName: add.js

  # 生成detail.vm
  - template: js/routes/detail.vm
    destDir: src/main/resources
    destPackage: react/routes
    destFileName: detail.js

  # 生成edit.vm
  - template: js/routes/edit.vm
    destDir: src/main/resources
    destPackage: react/routes
    destFileName: edit.js

  # 生成edit.vm
  - template: js/routes/index.vm
    destDir: src/main/resources
    destPackage: react/routes
    destFileName: index.js